CREATE TABLE MEMBER
(
    USERNO NUMBER PRIMARY KEY,
    USERID VARCHAR2(20) NOT NULL UNIQUE,
    USERPWD VARCHAR2(20) NOT NULL,
    USERNAME VARCHAR2(20) NOT NULL,
    PNO VARCHAR(14) NOT NULL,
    PHONE VARCHAR(11) NOT NULL,
    ADDRESS VARCHAR2(30),
    ENROLLDATE DATE DEFAULT SYSDATE NOT NULL
);